### ISSUE TITLE
arm support welcome

### ISSUE THREAD

**Issue by Fohlen** [RobCherry/docker-chromedriver#16]
Hey there @RobCherry 
I was thinking about offering cross-platform builds for arm.
Since I am on OSX the toolchain is quite easy to set up (no QUEMU required).
Would you like this to be supported? Would you mind pushing the images to the repository?

The aim here is to build a small aggregation tool that can work on my Raspberry Pi. That surely takes away a lot of hassle if it runs in a Docker container!

**Comment by RobCherry** [comment]
I would be all for integrating support for multiple architectures.  That is not something I have attempting yet (using manifest-tool), and I am not sure if/how Docker Hub supports automatically building for those, but any contributions are welcome.

**Comment by RobCherry** [comment]
No problem.  If you happen to use travis in your

**Comment by RobCherry** [comment]
Sorry, didn't mean to close this.

**Comment by Fohlen** [comment]
Hey, I added a PR under #17
