### ISSUE TITLE
Docker hub update dependencies

### ISSUE THREAD

**Issue by dmitryuk** [RobCherry/docker-chromedriver#20]
Is it possible to update "latest" dockerhub release? Because "robcherry/docker-chromedriver:latest" tag contains Chrome 66 and ChromeDriver 2.38.552522

**Comment by RobCherry** [comment]
I have pushed up tags `robcherry/docker-chromedriver:77`, `robcherry/docker-chromedriver:77.0.3865.40`, `robcherry/docker-chromedriver:headless-77` and `robcherry/docker-chromedriver:headless-77.0.3865.40`.  If someone could test it and let me know it works I will also update the `robcherry/docker-chromedriver:latest` and `robcherry/docker-chromedriver:headless` tags.

**Comment by RobCherry** [comment]
Note, the tag is based on the ChromeDriver version, not the Chrome version... I expect Chrome is actually running `77.0.3865.120` and not `77.0.3865.40`.

**Comment by RobCherry** [comment]
Also, important to note that it upgrades from Debian Jessie to Stretch...

**Comment by RobCherry** [comment]
Tagged previous image as `robcherry/docker-chromedriver:2.38.552522`.  Updated `latest` and `headless` tags.
